/*
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and2, the first 10 terms will be:
 *
 *1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 *By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 *find the sum of the even-valued terms.
 */

package e002_evenFibonnaciNumbers;

public class EvenFib {

	public static void main(String[] args) {

		int first = 0;
		int second = 1;

		int currentFib = 0;

		int sum = 0;

		while (currentFib <= 4000000) {
			if (first == 0) {
				currentFib = 1;
				first = 1;
			} else {
				currentFib = first + second;
				second = first;
				first = currentFib;
			}

			if (currentFib <= 4000000 && currentFib % 2 == 0)
				sum = sum + currentFib;
		}

		System.out
				.println("The sum of the even valued integers of the Fibonacci sequence,\nwhose values do not exceed 4 million: "
						+ sum + ".");

	}
}
